//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazProyectosDiverscan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponenteSistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComponenteSistema()
        {
            this.Respaldo = new HashSet<Respaldo>();
        }
    
        public int IdComponenteSistema { get; set; }
        public int IdSistema { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> FechaLiberacion { get; set; }
        public int IdDesarrollador { get; set; }
    
        public virtual Desarrolladores Desarrolladores { get; set; }
        public virtual Sistema Sistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respaldo> Respaldo { get; set; }
    }
}
